### ISSUE TITLE
Request: The White Box

### ISSUE THREAD

**Issue by captn3m0** [blr-today/ingest#16]
https://thewhiteboxco.in/ - similar events as trove

      List of events is at https://thewhiteboxco.in/collections/events-of-the-month/products.json

**Comment by captn3m0** [comment]
This is a shopify site, with very similar structure as Trove. Should be tackled after the trove migration

**Comment by captn3m0** [comment]
List of events is at https://thewhiteboxco.in/collections/events-of-the-month, but we want to use the JSON feed.

**Comment by captn3m0** [comment]
@surreal30 You wanna pick this up next?

**Comment by surreal30** [comment]
Yes. Will do. Please assign it to me.

This is similar to issue #21 , right?

**Comment by captn3m0** [comment]
Just pick it up. Assigning an issue is meaningless anyway in projects like this.

**Comment by captn3m0** [comment]
https://blr.today/cal/thewhitebox
