### ISSUE TITLE
Request: Parallel Cinema Club

### ISSUE THREAD

**Issue by captn3m0** [blr-today/ingest#25]
https://www.theparallelcinema.club/events

Apparently, this is a gatsby site, @karthikb351 can you publish the events in a JSON file somewhere perhaps?

**Comment by captn3m0** [comment]
Underline events are covered, so this is lower priority now.

**Comment by SantruptaMishra98** [comment]
Is there a format you want to provide the JSON? Like what fields would you require?

**Comment by captn3m0** [comment]
Best would be https://schema.org/ScreeningEvent, or an equivalent JSON dict that includes the following at the very least:

`startDate, endDate, inLanguage, workPresented.Movie.name (+URL), location, ticketURL`.

**Comment by captn3m0** [comment]
Changed to use Ghost now.

https://tpcc.club/events/ has some XHR requests.

**Comment by captn3m0** [comment]
Managed to extract data from the Elfsight calendar widget that is used on the homepage. Sadly it's all JS, so highly inaccessible and SEO-unfriendly.

**Comment by captn3m0** [comment]
Made a few suggestions towards improvements: https://talk.tpcc.club/t/event-calendar-improvements/48

**Comment by captn3m0** [comment]
Re-opening this, TPCC switched from elfsight to sanity.io as the backend.
