### ISSUE TITLE
Trove: Event names are null

### ISSUE THREAD

**Issue by lepisma** [blr-today/ingest#47]
![image](https://github.com/user-attachments/assets/85dc0462-235a-4c34-b65c-e0b3ba349c1d)

Trove events for recent database releases are not present resulting in `nulls` shown in the website. I did a quick check and the release [https://github.com/blr-today/dataset/releases/tag/v2024.9.23-12](v2024.9.23-12) had the correct field. Might be related to recent changes in Trove's ingestion?

**Comment by captn3m0** [comment]
Noticed it late last night, but the next event was on 28th so thought I'd fix it today. I put `title` instead of `name` I think.

**Comment by captn3m0** [comment]
Fixed now.
